#!/bin/sh

if [ ! -d "/var/app_root/backup" ]
then
    # making backup directory
    sudo mkdir -p /var/app_root/backup/
    sudo chown -R 1000 /var/app_root/
fi

if [ -d "/var/app_root/pyrin_framework" ]
then
    echo "Archiving and cleaning up previous installation."
    name=$(date "+%Y.%m.%d.%H.%M.%S")
    tar -czf /var/app_root/backup/"pyrin_framework.$name.tar.gz" /var/app_root/pyrin_framework
    sudo rm -r /var/app_root/pyrin_framework
else
    echo "Performing fresh installation."
fi

# making up required directory
sudo mkdir -p /var/app_root/pyrin_framework/app/
sudo chown -R 1000 /var/app_root/

echo "Copying applications."
# copying pyrin application
cp -r ../../src/pyrin/ /var/app_root/pyrin_framework/app/pyrin/

# copying pyrin tests
cp -r ../../src/tests/ /var/app_root/pyrin_framework/app/tests/
cp ../../src/start_test.py /var/app_root/pyrin_framework/app/start_test.py

# copying .env file
cp ../../src/.env /var/app_root/pyrin_framework/app/.env

# copying pipenv required files
cp ../../Pipfile.lock /var/app_root/pyrin_framework/Pipfile.lock
cp ../../Pipfile /var/app_root/pyrin_framework/Pipfile

# setting the owner of directory
sudo chown -R 1000 /var/app_root/

# setting up pipenv environment
cd /var/app_root/pyrin_framework/
export PIPENV_VENV_IN_PROJECT=1
pipenv install --ignore-pipfile
